### ISSUE TITLE
make a cron to run everyday at 08:00:01

### ISSUE THREAD

**Issue by arno1190** [ClementWalter/RainBot#3]

**Comment by ClementWalter** [comment]
Hi Arnault, thanks for your feedback. I'll be working on it ASAP, expecting a release before tomorrow morning.

**Comment by arno1190** [comment]
perfect, thanks

**Comment by ClementWalter** [comment]
This should add the requested feature : c0dce4fce908c5f67050cde15f783abc7561d9b4
